// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WildfireSimulator.Infrastructure.Data;

#nullable disable

namespace WildfireSimulator.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WildfireSimulator.Domain.Models.ActiveSimulationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SimulationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StepResultsData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("TotalBurnedCells")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBurningCells")
                        .HasColumnType("integer");

                    b.Property<string>("WeatherData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("IsRunning");

                    b.HasIndex("SimulationId")
                        .IsUnique();

                    b.ToTable("ActiveSimulationRecords");
                });

            modelBuilder.Entity("WildfireSimulator.Domain.Models.FireMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageWindSpeed")
                        .HasColumnType("double precision");

                    b.Property<int>("BurnedCellsCount")
                        .HasColumnType("integer");

                    b.Property<int>("BurningCellsCount")
                        .HasColumnType("integer");

                    b.Property<double>("FireSpreadSpeed")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalCellsAffected")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("SimulationId", "Step")
                        .IsUnique();

                    b.ToTable("FireMetrics");
                });

            modelBuilder.Entity("WildfireSimulator.Domain.Models.Simulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitialFirePositions")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SerializedGraph")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WeatherConditionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("WeatherConditionId");

                    b.ToTable("Simulations");
                });

            modelBuilder.Entity("WildfireSimulator.Domain.Models.WeatherCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Humidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("Precipitation")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WindDirection")
                        .HasColumnType("integer");

                    b.Property<double>("WindDirectionDegrees")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeedMps")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("WeatherConditions");
                });

            modelBuilder.Entity("WildfireSimulator.Domain.Models.ActiveSimulationRecord", b =>
                {
                    b.HasOne("WildfireSimulator.Domain.Models.Simulation", "Simulation")
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("WildfireSimulator.Domain.Models.FireMetrics", b =>
                {
                    b.HasOne("WildfireSimulator.Domain.Models.Simulation", "Simulation")
                        .WithMany("Metrics")
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("WildfireSimulator.Domain.Models.Simulation", b =>
                {
                    b.HasOne("WildfireSimulator.Domain.Models.WeatherCondition", "WeatherCondition")
                        .WithMany()
                        .HasForeignKey("WeatherConditionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("WildfireSimulator.Domain.Models.SimulationParameters", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("SimulationId")
                                .HasColumnType("uuid");

                            b1.Property<double>("ElevationVariation")
                                .HasPrecision(8, 2)
                                .HasColumnType("double precision");

                            b1.Property<int>("GraphType")
                                .HasColumnType("integer");

                            b1.Property<int>("GridHeight")
                                .HasColumnType("integer");

                            b1.Property<int>("GridWidth")
                                .HasColumnType("integer");

                            b1.Property<int>("InitialFireCellsCount")
                                .HasColumnType("integer");

                            b1.Property<double>("InitialMoistureMax")
                                .HasPrecision(3, 2)
                                .HasColumnType("double precision");

                            b1.Property<double>("InitialMoistureMin")
                                .HasPrecision(3, 2)
                                .HasColumnType("double precision");

                            b1.Property<int?>("RandomSeed")
                                .HasColumnType("integer");

                            b1.Property<int>("SimulationSteps")
                                .HasColumnType("integer");

                            b1.Property<int>("StepDurationSeconds")
                                .HasColumnType("integer");

                            b1.Property<string>("VegetationDistributionsJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("VegetationDistributions");

                            b1.HasKey("SimulationId");

                            b1.ToTable("Simulations");

                            b1.WithOwner()
                                .HasForeignKey("SimulationId");
                        });

                    b.Navigation("Parameters")
                        .IsRequired();

                    b.Navigation("WeatherCondition");
                });

            modelBuilder.Entity("WildfireSimulator.Domain.Models.Simulation", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
